
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes-app
  template:
    metadata:
      labels:
        app: kubernetes-app
        tier: frontend
        track: stable
    spec:
      containers:
        - name: user
          image: "grajamca/kubernetes-app:1.0.0"
          ports:
            - name: kubernetes-app
              containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-app
spec:
  selector:
    app: kubernetes-app
    tier: frontend
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8001
      targetPort: kubernetes-app
