name: Build pipeline
on:
  push:
    branches:
      - master
env:
  DOCKER_IMAGE: grajamca/kubernetes-app
  TAG: 1.0.0

jobs:
  setup-build-pipeline:
    name: Setting up build pipeline
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v2

      - name: Use Node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Install dependency
        run: npm install

      - name: Package
        run: npm run build

      - name: Docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Docker build
        run: |
          docker build -t $DOCKER_IMAGE:$TAG .
      - name: Docker push
        run: |
          docker push $DOCKER_IMAGE:$TAG
